### PR TITLE
Fix emoji spacing on linux

### LINKED ISSUE #7: Inconsistent emoji spacing in logs on Linux
On Linux, logging all levels other than warn results in the emoji and message being jammed together without a separating space.

I will submit a fix.

### PR DESCRIPTION
**Pull request by rthadr**
This resolves #7.  Modified `isWideEmoji` to return false on Linux.  Now spacing is consistent between emoji and message (tested on bash).

### CODE REVIEW

**Comment by kdubb** [comment]
I think this more has to do with terminal type (e.g. `echo $TERM`) mode than the platform.  I want to see if we can figure out which terminal is spaces correctly vs incorrectly.

I use macOS and the default for `Terminal.app` is `ansi`, I think linux defaults to `xterm`.

**Comment by kdubb** [comment]
Detecting the terminal type might also be a more reliable way to fix #6. A 3rd party terminal on Windows might display things correctly vs native terminals.

**Comment by rthadr** [comment]
Ok, I will look into that.

**Comment by rthadr** [comment]
zsh on Catalina:  echo $TERM returns xterm-256color
bash on WSL (Ubuntu): same

However, the spacing is different.  So, I think $TERM is out as a method of detection.  This might have to be a human settable option.  I'll continue digging a bit first, though.

**Comment by kdubb** [comment]
Actually you are correct. I think always import my settings for `zsh` and `Terminal.app` upon fresh install it must have been a holdover from a previous version.  I just reset it to `xterm-256color`.

**Comment by rthadr** [comment]
I'm going to take a different direction on this (need to think a bit, too).  Abandoning this branch.

**Comment by kdubb** [comment]
@rthadr Thanks for all the help and work on this!

**Comment by rthadr** [comment]
Thank you for allowing me to contribute.  This is fun for me.

**Pull request closed without merging**
