### PR TITLE
Do not mutate errors

### PR DESCRIPTION
**Pull request by rthadr**
First, thanks for creating this.  I stumbled across it on npm when pino colada wasn't fitting my needs.  We are using this library for logging during development (the logs are great!), but I noticed that some properties are stripped from the error responses (message, namely), when used as a direct prettifier.  This PR should take care of that while preserving the existing output format.

### CODE REVIEW

**Comment by kdubb** [comment]
Thanks! The "pretty" logs are specifically for development and JSON is for production; so I couldn't deal with all the missing information in the other prettifiers.

~Am I correctly reading this as it doesn't change the output format but just ensures the error can be passed on after passing it to miami-vice?~ Apparently I didn't read your entire message!

**Comment by rthadr** [comment]
Thanks, for responding so quickly.  I tried to force-push to fix some formatting, but it looks like the changeset is exactly the same so it's safe to ignore.  No rush on publishing or anything as I just pointed our package.json to my fork.

**Comment by rthadr** [comment]
Off Topic, I realize, but what do you think about the palm tree emoji 🌴 for info?  I mean it **IS** Miami Vice, after all, right?

**Comment by rthadr** [comment]
Sorry, for the traffic on this, but I'm going to clean up these PRs and then resubmit with corresponding issues.  I have a couple of other enhancements, too.

**Pull request closed without merging**
